### ISSUE TITLE
--singleWindow issues with FF

### ISSUE THREAD

**Issue by rvalle** [FrozenCanuck/Lebowski#20]
I am experimenting different testing results when using --singleWindow in FF 3.6.20

Lebowski seems to fail to "click" a segment view when in singleWindow mode.

When running without the switch it all works fine. 

Without having looked into this, I think there is a click positioning issue. 

I also have the feeling that scrolling up/down has something to do. FF seems to scroll down when Lebowski updates controls otherwise not visible in the page.

has anybody also experienced this?

**Comment by FrozenCanuck** [comment]
Yeah, working with single window mode will not work with Lebowski when trying to test your SC web app since the app gets loaded into an iframe. When you initialize the main application, Lebowski looks for the app's root object in the top-level window. So when you do a single window mode, Lebowski can't find that root object because it's now in frame. 

Is there a reason why you want to use selenium's single mode feature? Selenium was intentionally moved away from single mode as a default since it did end up causing problems for apps under test.

**Comment by rvalle** [comment]
that's strange, It did work before... 

NO, I have no particular reason other than not ending with 100s of FireFox windows all over the place.

That setting allow me to get only half of them. It was nothing, just cosmetic.
